# This is a basic workflow to help you get started with Actions

name: Member Add

on:
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List members
        run: |
          while read p; do
            echo "$p"
          done < members.txt
      - name: Add members
        run: |
          while read p; do
            curl \
              -X PUT \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ORG_TOKEN }}" \
              https://api.github.com/orgs/test-member-admin/teams/aa/memberships/"$p" \
              -d '{"role":"member"}'
          done < members.txt

